"""add equipped item models

Revision ID: fc363d3eaec6
Revises: 40c8636d40b7
Create Date: 2025-06-03 12:56:08.562051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc363d3eaec6"
down_revision: Union[str, None] = "40c8636d40b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_items",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["store_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "users", sa.Column("equipped_accessory_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("equipped_background_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "users", "store_items", ["equipped_accessory_id"], ["id"]
    )
    op.create_foreign_key(
        None, "users", "store_items", ["equipped_background_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "equipped_background_id")
    op.drop_column("users", "equipped_accessory_id")
    op.drop_table("user_items")
    # ### end Alembic commands ###
