"""add date to diary

Revision ID: c295c59eae4f
Revises: 5131879f46a5
Create Date: 2025-06-08 20:57:32.713027

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c295c59eae4f"
down_revision: Union[str, None] = "5131879f46a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("diaries", sa.Column("date", sa.Date(), nullable=True))
    op.execute("UPDATE diaries SET date = DATE(created_at) WHERE date IS NULL;")
    op.alter_column("diaries", "date", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("diaries", "date")
    # ### end Alembic commands ###
