"""fix category column length

Revision ID: 40c8636d40b7
Revises: 9068d50bc5be
Create Date: 2025-06-03 12:01:13.548137

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40c8636d40b7"
down_revision: Union[str, None] = "9068d50bc5be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store_items",
        "category",
        existing_type=sa.VARCHAR(length=6),
        type_=sa.String(length=12),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "store_items",
        "category",
        existing_type=sa.String(length=12),
        type_=sa.VARCHAR(length=6),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
