"""remove date column in diary

Revision ID: 49842c2d21a0
Revises: bf7bec963808
Create Date: 2025-05-29 19:43:52.029297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "49842c2d21a0"
down_revision: Union[str, None] = "bf7bec963808"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_items",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=6), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("image_url", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("diaries", "date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "diaries", sa.Column("date", sa.DATE(), autoincrement=False, nullable=False)
    )
    op.drop_table("store_items")
    # ### end Alembic commands ###
