"""add coin column

Revision ID: bf7bec963808
Revises: 07a05f1becd0
Create Date: 2025-05-28 17:22:03.643549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf7bec963808"
down_revision: Union[str, None] = "07a05f1becd0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("coin", sa.Integer(), nullable=False, server_default="0")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "coin")
    # ### end Alembic commands ###
